DROP  TABLE RXNCONSO;
CREATE TABLE RXNCONSO
(
   RXCUI VARCHAR2(8) NOT NULL,
   LAT VARCHAR2 (3) DEFAULT 'ENG' NOT NULL,
   TS VARCHAR2 (1),
   LUI VARCHAR2(8),
   STT VARCHAR2 (3),
   SUI VARCHAR2 (8),
   ISPREF VARCHAR2 (1),
   RXAUI  VARCHAR2(8) NOT NULL,
   SAUI VARCHAR2 (50),
   SCUI VARCHAR2 (50),
   SDUI VARCHAR2 (50),
   SAB VARCHAR2 (20) NOT NULL,
   TTY VARCHAR2 (20) NOT NULL,
   CODE VARCHAR2 (50) NOT NULL,
   STR VARCHAR2 (3000) NOT NULL,
   SRL VARCHAR2 (10),
   SUPPRESS VARCHAR2 (1),
   CVF VARCHAR2(50)
)
;

DROP TABLE RXNREL;
CREATE TABLE RXNREL
(
   RXCUI1    VARCHAR2(8) ,
   RXAUI1    VARCHAR2(8), 
   STYPE1    VARCHAR2(50),
   REL       VARCHAR2(4) ,
   RXCUI2    VARCHAR2(8) ,
   RXAUI2    VARCHAR2(8),
   STYPE2    VARCHAR2(50),
   RELA      VARCHAR2(100) ,
   RUI       VARCHAR2(10),
   SRUI      VARCHAR2(50),
   SAB       VARCHAR2(20) NOT NULL,
   SL        VARCHAR2(1000),
   DIR       VARCHAR2(1),
   RG        VARCHAR2(10),
   SUPPRESS  VARCHAR2(1),
   CVF       VARCHAR2(50)
)
;


DROP TABLE RXNSAT;
CREATE TABLE RXNSAT
(
   RXCUI VARCHAR2(8),
   LUI VARCHAR2(8),
   SUI VARCHAR2(8),
   RXAUI VARCHAR2(8),
   STYPE VARCHAR2 (50),
   CODE VARCHAR2 (50),
   ATUI VARCHAR2(11),
   SATUI VARCHAR2 (50),
   ATN VARCHAR2 (1000) NOT NULL,
   SAB VARCHAR2 (20) NOT NULL,
   ATV VARCHAR2 (4000),
   SUPPRESS VARCHAR2 (1),
   CVF VARCHAR2 (50)
)
;
