site_name: Medical Action Ontology (Documentation)
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.code.select
plugins:
  - search
markdown_extensions:
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - attr_list
  - md_in_html
  - tables
site_url: https://github.com/monarch-initiative/MAxO
repo_url: https://github.com/monarch-initiative/MAxO

extra_css:
  - css/custom.css
